export const staticLabels = {
  firstName: "First Name",
  middleName: "Middle Name",
  lastName: "Last Name",
  mobileNumber: "Mobile Number",
  gender: "Gender",
  dob: "Date of Birth",
  email: "Email Address",
  aadharQuestion: "Do you currently stay at your Aadhaar address?",
  residenceType: "Select your residence type",
  pinCode: "Pin Code",
  flatHouseAppartment: "Flat No. / House No. / Appartment",
  localitySociety: "Locality / Society/ Colony Name",
  landMark: "Landmark",
  state: "State",
  city: "City",
  occupationType: "Occupation Type",
  companyName: "Name of the Company",
  businessProfession: "Profession or Designation",
  businessName: "Business or Shop Name",
  designation: "Designation",
  annualGross: "Annual Gross Income",
  totalExperience: "Total Year of experience",
  salaryAccount: "Salary Account",
  proofOfIncome: "Proof of Income",
  annualFee: "Annual Fees",
  joiningFee: "Joining Fees",
  features: "Features",
  welcome: "Welcome Offer",
  officeAddress: "Office Address",
  aadharCard: "Aadhaar Card",
  panCard: "PAN Card",
  personalDetails: "Personal Details",
  officeDetails: "Office Details",
};
