export const staticLabels = {
  firstName: "Name as per PAN",
  middleName: "Middle Name as per PAN",
  lastName: "Last Name as per PAN",
  yourName: "Your Name",
  mobileNumber: "Mobile Number",
  gender: "Gender",
  dob: "Date of Birth",
  emailInput: "E-Mail",
  email: "Email Address",
  aadharQuestion: "Is this your Aadhar Address ?",
  note: "We will be considering this as your permanent address",
  residenceType: "Select your residence type",
  pinCode: "Pin Code",
  flatHouseAppartment: "Flat No. / House No. / Appartment",
  localitySociety: "Locality / Society/ Colony Name",
  landMark: "Landmark * Optional",
  state: "State",
  city: "City",
  occupationType: "Occupation Type",
  companyName: "Company Name",
  department: "Department",
  businessProfession: "Profession or Designation",
  businessName: "Business or Shop Name",
  designation: "Designation",
  annualGross: "Annual Gross Income",
  totalExperience: "Total Year of experience",
  salaryAccount: "Salary Account",
  proofOfIncome: "Proof of Income",
  annualFee: "Annual Fees",
  joiningFee: "Joining Fees",
  features: "Features",
  welcome: "Welcome Offer",
  officeAddress: "Office Address",
  aadharCard: "Aadhaar Card",
  panCard: "PAN Card",
  personalDetails: "Personal Details",
  officeDetails: "Office Details",
  address1: "Address #1",
  address2: "Address #2",
  address3: "Address #3",
  monthlyIncome: "Monthly Income",
  annualItr: "Annual ITR",
  selectBank: "Select Bank",
  selectedAggregator: "Select account aggregator",
  registeredNo: "Registered Mobile No.",
  customerId: "Customer ID",
  password: "Password",
  nameOnCard: "Name on Card",
};
